<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="FirstFlow" targetNamespace="http://FirstFlow" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://FirstFlow" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="FirstFlowHttpBinding" originalBindingStyle="document"/>
        <generatedXSD location="FirstFlow_InlineSchema1.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
    
        <xsd:schema targetNamespace="http://FirstFlow" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
      <xsd:include schemaLocation="FirstFlow_InlineSchema1.xsd"/>
    </xsd:schema>
    </wsdl:types>
  <wsdl:message name="getAllUsersRequestMsg">
    <wsdl:part element="tns:getAllUsers" name="getAllUsersParameters"/>
  </wsdl:message>
  <wsdl:message name="getAllUsersResponseMsg">
    <wsdl:part element="tns:getAllUsersResponse" name="getAllUsersResult"/>
  </wsdl:message>
  <wsdl:portType name="FirstFlow">
    <wsdl:operation name="getAllUsers">
      <wsdl:input message="tns:getAllUsersRequestMsg" name="getAllUsersRequest"/>
      <wsdl:output message="tns:getAllUsersResponseMsg" name="getAllUsersResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="FirstFlowHttpBinding" type="tns:FirstFlow">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getAllUsers">
      <soap:operation soapAction="http://FirstFlow/getAllUsers"/>
      <wsdl:input name="getAllUsersRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getAllUsersResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    </wsdl:binding>
  <wsdl:service name="FirstFlowHttpService">
    <wsdl:port binding="tns:FirstFlowHttpBinding" name="FirstFlowHttpPort">
      <soap:address location="http://localhost:7800/FirstFlow"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>